### ISSUE TITLE
raise wrong Exception: Invalid ResourceConsumption of Implementation

### ISSUE THREAD

**Issue by Trevn-Wang** [melodypapa/py-armodel#22]
Some of Arxml do not have RESOURCE-CONSUMPTION in its SWC-IMPLEMENTATION in AUTOSAR version 4.0.3
![image](https://github.com/user-attachments/assets/3f8371a5-6383-4184-a6db-7b7e9e01fcc4)

**Comment by melodypapa** [comment]
Will you provide the ARXML for analysis?
